In [2]:
import torch
import tiktoken

In [3]:
raw_text = "This is my dog Hazel"

In [5]:
tokenizer = tiktoken.get_encoding("gpt2")

In [6]:
enc_text = tokenizer.encode( raw_text )
print(enc_text)

[1212, 318, 616, 3290, 42805]


In [7]:
vocab_size = 5
output_dim = 4
inputs = torch.nn.Embedding( vocab_size, output_dim )
print( inputs.weight )

Parameter containing:
tensor([[ 0.3914, -0.7047, -0.3112,  0.0725],
        [-0.8383,  2.0826, -1.3546, -0.7066],
        [-0.5931, -0.6351, -0.7820,  1.4764],
        [ 1.2772, -0.1829, -0.3945,  0.1175],
        [ 0.8090,  0.2978, -1.1922, -1.4292]], requires_grad=True)


In [8]:
inputs = inputs.weight.data 
inputs

tensor([[ 0.3914, -0.7047, -0.3112,  0.0725],
        [-0.8383,  2.0826, -1.3546, -0.7066],
        [-0.5931, -0.6351, -0.7820,  1.4764],
        [ 1.2772, -0.1829, -0.3945,  0.1175],
        [ 0.8090,  0.2978, -1.1922, -1.4292]])

In [10]:
inputs.shape

torch.Size([5, 4])

In [12]:
for row in inputs:
    print(row.tolist())

[0.391354501247406, -0.7046935558319092, -0.3112082779407501, 0.072487972676754]
[-0.8383475542068481, 2.0826263427734375, -1.3546010255813599, -0.7066236138343811]
[-0.5930670499801636, -0.6350643634796143, -0.7820141911506653, 1.4764204025268555]
[1.2771680355072021, -0.18288226425647736, -0.3944859802722931, 0.11750861257314682]
[0.808978259563446, 0.2978053390979767, -1.192151665687561, -1.4292271137237549]


In [13]:
x = torch.Tensor([1.1, 2.3])
y = torch.Tensor([3.4,-2.1])


In [14]:
1.1*3.4 + 2.3*(-2.1)

-1.0899999999999999

In [15]:
torch.dot( x, y)

tensor(-1.0900)

In [16]:
query = inputs[2]
print(query)

tensor([-0.5931, -0.6351, -0.7820,  1.4764])


In [17]:
for i in range( len( inputs )):
    print( torch.dot( query, inputs[i] ) )

tensor(0.5658)
tensor(-0.8094)
tensor(3.5464)
tensor(-0.1593)
tensor(-1.8468)


In [21]:
attention_scores_2 = torch.zeros( len(inputs) )
for i in range( len( inputs )):
    attention_scores_2[i] = torch.dot( query, inputs[i] )
print( attention_scores_2)

tensor([ 0.5658, -0.8094,  3.5464, -0.1593, -1.8468])


In [23]:
# normalize the attention scores using the softmax function:
# def softmax(x):
#     torch.exp(x) / torch.exp(x).sum()

In [29]:
attention_scores_2 = torch.softmax( attention_scores_2, dim = 0 )
attention_scores_2

tensor([0.1591, 0.1537, 0.3793, 0.1554, 0.1525])

In [30]:
attention_scores_2.sum()

tensor(1.0000)

In [31]:
context_vector_2 = torch.zeros( query.shape )
for i in range( len( attention_scores_2 ) ):
    context_vector_2 += attention_scores_2[i]*inputs[i] 
context_vector_2

tensor([ 0.0303, -0.0159, -0.7975,  0.2632])