In [1]:
import torch
import tiktoken

In [2]:
raw_text = "This is my dog Hazel"

In [3]:
tokenizer = tiktoken.get_encoding("gpt2")

In [4]:
enc_text = tokenizer.encode( raw_text )
print(enc_text)

[1212, 318, 616, 3290, 42805]


In [5]:
vocab_size = 5
output_dim = 4
inputs = torch.nn.Embedding( vocab_size, output_dim )
print( inputs.weight )

Parameter containing:
tensor([[ 5.5549e-01, -4.5127e-01, -2.8023e-01,  2.0503e+00],
        [-9.6818e-01, -1.1042e+00,  1.8840e+00,  3.5029e-01],
        [ 4.7728e-01, -8.3923e-01, -7.1929e-01, -5.2904e-01],
        [-9.5396e-01,  1.0014e+00, -1.3068e-03, -1.8068e+00],
        [-2.6922e+00, -6.0866e-01,  1.3370e+00, -1.0332e+00]],
       requires_grad=True)


In [6]:
inputs = inputs.weight.data 
inputs

tensor([[ 5.5549e-01, -4.5127e-01, -2.8023e-01,  2.0503e+00],
        [-9.6818e-01, -1.1042e+00,  1.8840e+00,  3.5029e-01],
        [ 4.7728e-01, -8.3923e-01, -7.1929e-01, -5.2904e-01],
        [-9.5396e-01,  1.0014e+00, -1.3068e-03, -1.8068e+00],
        [-2.6922e+00, -6.0866e-01,  1.3370e+00, -1.0332e+00]])

In [7]:
inputs.shape

torch.Size([5, 4])

In [8]:
for row in inputs:
    print(row.tolist())

[0.5554900765419006, -0.45127108693122864, -0.2802272439002991, 2.050279140472412]
[-0.9681820869445801, -1.104203701019287, 1.8840079307556152, 0.3502862751483917]
[0.47727930545806885, -0.8392347097396851, -0.7192875742912292, -0.5290370583534241]
[-0.9539591073989868, 1.0013759136199951, -0.0013067919062450528, -1.8068374395370483]
[-2.692190170288086, -0.6086598038673401, 1.3370273113250732, -1.0331642627716064]


In [9]:
x = torch.Tensor([1.1, 2.3])
y = torch.Tensor([3.4,-2.1])


In [10]:
1.1*3.4 + 2.3*(-2.1)

-1.0899999999999999

In [11]:
torch.dot( x, y)

tensor(-1.0900)

In [12]:
query = inputs[2]
print(query)

tensor([ 0.4773, -0.8392, -0.7193, -0.5290])


In [13]:
for i in range( len( inputs )):
    print( torch.dot( query, inputs[i] ) )

tensor(-0.2393)
tensor(-1.0759)
tensor(1.7294)
tensor(-0.3389)
tensor(-1.1892)


In [14]:
attention_scores_2 = torch.zeros( len(inputs) )
for i in range( len( inputs )):
    attention_scores_2[i] = torch.dot( query, inputs[i] )
print( attention_scores_2)

tensor([-0.2393, -1.0759,  1.7294, -0.3389, -1.1892])


In [15]:
# normalize the attention scores using the softmax function:
# def softmax(x):
#     torch.exp(x) / torch.exp(x).sum()

In [16]:
attention_scores_2 = torch.softmax( attention_scores_2, dim = 0 )
attention_scores_2

tensor([0.1012, 0.0438, 0.7243, 0.0916, 0.0391])

In [17]:
attention_scores_2.sum()

tensor(1.)

In [18]:
context_vector_2 = torch.zeros( query.shape )
for i in range( len( attention_scores_2 ) ):
    context_vector_2 += attention_scores_2[i]*inputs[i] 
context_vector_2

tensor([ 0.1668, -0.6340, -0.4146, -0.3663])