In [1]:
import torch
import torch.nn as nn

In [15]:
# one way to make some typical input:
input = torch.randn( 1, 3 )
input

tensor([[ 0.5047, -1.2738,  0.7399]])

In [3]:
input = torch.tensor([[ 1.0, 2.0, 3.0 ]])
input

tensor([[1., 2., 3.]])

In [16]:
# a simple neural network:
model = nn.Sequential(
    # a layer that takes 3 inputs, gives 2 outputs
    nn.Linear( 3, 2 ),
    # a nonlinear activation function
    nn.ReLU(),
    # output layer takes 2 inputs, gives scalar output
    nn.Linear( 2, 1)
)

In [6]:
model[0].weight.data = torch.tensor([[ 2.0, 1.0, -1.0 ],
                                     [ -2.0, -1.0, 1.0 ]])
model[0].weight.data

tensor([[ 2.,  1., -1.],
        [-2., -1.,  1.]])

In [7]:
model[0].bias.data = torch.tensor([[0.0, 0.0]])

In [17]:
model[0].weight.data

tensor([[ 0.3595,  0.0444, -0.0930],
        [-0.4406, -0.3730, -0.3911]])

In [18]:
model[0].bias.data

tensor([ 0.3429, -0.1515])

In [19]:
input @ model[0].weight.data.T + model[0].bias.data

tensor([[ 0.3990, -0.1881]])

In [20]:
activation = nn.ReLU()
middle = activation( input @ model[0].weight.data.T + model[0].bias.data)
middle

tensor([[0.3990, 0.0000]])

In [21]:
middle @ model[2].weight.data.T + model[2].bias.data

tensor([[0.3317]])

In [25]:
model[2].weight.data.T

tensor([[-0.3857],
        [-0.3228]])

In [22]:
model(input)

tensor([[0.3317]], grad_fn=<AddmmBackward0>)